apiVersion: v1
kind: Secret
metadata:
  name: diary-vue-db-creds
  namespace: diary-vue
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm5zal9yb290XzU3NWEwMTE0YzNmNzFmODg=
  MYSQL_DATABASE: aW52ZXN0X2RpYXJ5
  MYSQL_USER: ZGlhcnl2dWU=
  MYSQL_PASSWORD: cHV2Q2pBTGF0N2RhMWFCWXo0SUx1THFv
  DATABASE_URL: bXlzcWw6Ly9kaWFyeXZ1ZTpwdXZDakFMYXQ3ZGExYUJZejRJTHVMcW9AZGlhcnktdnVlLWRiLmRpYXJ5LXZ1ZS5zdmMuY2x1c3Rlci5sb2NhbDozMzA2L2ludmVzdF9kaWFyeQ==
