import { describe, expect, it } from 'vitest'
import { generatePricePoints, parseTargetPrices } from '~/lib/relativeValue'

describe('relative value helpers', () => {
  it('filters out non-positive autogenerated price points', () => {
    expect(generatePricePoints(10, 5, 3, 'both')).toEqual([1, 4, 7, 13, 16, 19, 22, 25])
    expect(generatePricePoints(10, 5, 10, 'down')).toEqual([])
  })

  it('rejects invalid generator inputs', () => {
    expect(generatePricePoints(0, 5, 10, 'both')).toEqual([])
    expect(generatePricePoints(100, 0, 10, 'both')).toEqual([])
    expect(generatePricePoints(100, 5, 0, 'both')).toEqual([])
  })

  it('parses positive target prices, removes invalid values, and deduplicates', () => {
    expect(parseTargetPrices('5200, 5150\n5100 foo 0 -3 5200')).toEqual([5100, 5150, 5200])
  })
})
