<script setup lang="ts">
import {
  monthlyData,
  getMonthName,
  getMonthShortName,
  getVolatilityLabel,
  getStrengthLabel,
  getMonthStrength,
  formatReturn,
  getReturnColorClass,
  getVolatilityColorClass,
  getBestMonths,
  getWorstMonths,
  calculatePeriodAvgReturn,
  analyzeSeasonality
} from '~/utils/stockSeasonality'
import type { VolatilityLevel } from '~/utils/stockSeasonality'

const { t, locale } = useI18n()
const toast = useToast()

// Get current month (1-12)
const currentMonth = new Date().getMonth() + 1
const nextMonth = currentMonth === 12 ? 1 : currentMonth + 1

// Current and next month data
const currentMonthData = computed(() => monthlyData.find(m => m.month === currentMonth)!)
const nextMonthData = computed(() => monthlyData.find(m => m.month === nextMonth)!)

// Best and worst months
const bestMonths = computed(() => getBestMonths(3))
const worstMonths = computed(() => getWorstMonths(3))

// Period analysis
const strongPeriodMonths = [11, 12, 1, 2, 3, 4]
const weakPeriodMonths = [5, 6, 7, 8, 9, 10]

const strongPeriodReturn = computed(() => calculatePeriodAvgReturn(strongPeriodMonths))
const weakPeriodReturn = computed(() => calculatePeriodAvgReturn(weakPeriodMonths))

// Full analysis
const analysis = computed(() => analyzeSeasonality())

// Localized month name helper
const getLocalizedName = (month: number) => getMonthName(month, locale.value)
const getLocalizedShortName = (month: number) => getMonthShortName(month, locale.value)
const getLocalizedVolatility = (volatility: VolatilityLevel) => getVolatilityLabel(volatility, locale.value)
const getLocalizedStrength = (avgReturn: number) => getStrengthLabel(getMonthStrength(avgReturn), locale.value)

// Get localized characteristics using i18n
const getCharacteristics = (month: number) => {
  const monthData = monthlyData.find(m => m.month === month)
  if (!monthData) return ''
  return t(monthData.characteristicsKey)
}

// Copy to clipboard
const copySuccess = ref(false)

const copyToClipboard = async () => {
  const lines: string[] = []
  
  if (locale.value === 'en') {
    lines.push('# US Stock Market Seasonality Analysis')
    lines.push('')
    lines.push('> Based on historical data from 1950 to present. Statistical patterns, not absolute predictions.')
    lines.push('')
    
    lines.push('## Monthly Performance Overview')
    lines.push('')
    lines.push('| Month | Avg Return | Characteristics | Volatility |')
    lines.push('|-------|------------|-----------------|------------|')
    
    for (const data of monthlyData) {
      lines.push(`| ${getMonthShortName(data.month, 'en')} | ${formatReturn(data.avgReturn)} | ${t(data.characteristicsKey, 'en')} | ${getVolatilityLabel(data.volatility, 'en')} |`)
    }
  } else {
    const isTraditional = locale.value === 'zh-TW'
    lines.push(isTraditional ? '# 美股月份季節性分析' : '# 美股月份季节性分析')
    lines.push('')
    lines.push(isTraditional 
      ? '> 基於1950年至今的歷史數據統計，為統計模式而非絕對預測。'
      : '> 基于1950年至今的历史数据统计，为统计模式而非绝对预测。')
    lines.push('')
    
    lines.push(isTraditional ? '## 月份表現概覽' : '## 月份表现概览')
    lines.push('')
    lines.push('| 月份 | 平均回報 | 主要特性 | 波動性 |')
    lines.push('|------|----------|----------|--------|')
    
    for (const data of monthlyData) {
      lines.push(`| ${getMonthShortName(data.month, locale.value)} | ${formatReturn(data.avgReturn)} | ${t(data.characteristicsKey)} | ${getVolatilityLabel(data.volatility, locale.value)} |`)
    }
  }
  
  lines.push('')
  lines.push('---')
  lines.push(`*Generated by Stock Seasonality Analyzer*`)
  
  const markdown = lines.join('\n')
  
  try {
    await navigator.clipboard.writeText(markdown)
    copySuccess.value = true
    toast.success(t('tools.seasonality.copySuccess'))
    setTimeout(() => {
      copySuccess.value = false
    }, 2000)
  } catch (err) {
    toast.error(t('tools.seasonality.copyFailed'))
  }
}

// SEO
useHead({
  title: '美股月份季節性分析 - 投資工具',
  meta: [
    { name: 'description', content: '基於1950年至今的歷史數據，分析美股S&P 500月份季節性模式，了解最佳與最差月份，輔助投資決策。' }
  ]
})

// Set page meta for public access
definePageMeta({
  requiresAuth: false
})
</script>

<template>
  <div class="max-w-4xl mx-auto">
    <!-- Header -->
    <div class="text-center mb-8">
      <h1 class="text-3xl font-bold text-gray-900 dark:text-white mb-2">
        {{ t('tools.seasonality.title') }}
      </h1>
      <p class="text-gray-600 dark:text-gray-400">
        {{ t('tools.seasonality.subtitle') }}
      </p>
    </div>

    <!-- Current & Next Month Highlight -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
      <!-- Current Month -->
      <div class="bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl shadow-lg p-6 text-white">
        <div class="flex items-center justify-between mb-4">
          <span class="text-sm font-medium opacity-80">{{ t('tools.seasonality.currentMonth') }}</span>
          <span class="px-3 py-1 bg-white/20 rounded-full text-xs font-medium">
            {{ getLocalizedStrength(currentMonthData.avgReturn) }}
          </span>
        </div>
        <h2 class="text-3xl font-bold mb-2">{{ getLocalizedName(currentMonth) }}</h2>
        <div class="text-4xl font-bold mb-3">
          {{ formatReturn(currentMonthData.avgReturn) }}
        </div>
        <p class="text-sm opacity-90 mb-4">{{ getCharacteristics(currentMonth) }}</p>
        <div class="flex items-center gap-2">
          <span class="text-xs opacity-70">{{ t('tools.seasonality.volatility') }}:</span>
          <span class="px-2 py-0.5 bg-white/20 rounded text-xs">{{ getLocalizedVolatility(currentMonthData.volatility) }}</span>
        </div>
      </div>

      <!-- Next Month -->
      <div class="bg-gradient-to-br from-emerald-500 to-teal-600 rounded-xl shadow-lg p-6 text-white">
        <div class="flex items-center justify-between mb-4">
          <span class="text-sm font-medium opacity-80">{{ t('tools.seasonality.nextMonth') }}</span>
          <span class="px-3 py-1 bg-white/20 rounded-full text-xs font-medium">
            {{ getLocalizedStrength(nextMonthData.avgReturn) }}
          </span>
        </div>
        <h2 class="text-3xl font-bold mb-2">{{ getLocalizedName(nextMonth) }}</h2>
        <div class="text-4xl font-bold mb-3">
          {{ formatReturn(nextMonthData.avgReturn) }}
        </div>
        <p class="text-sm opacity-90 mb-4">{{ getCharacteristics(nextMonth) }}</p>
        <div class="flex items-center gap-2">
          <span class="text-xs opacity-70">{{ t('tools.seasonality.volatility') }}:</span>
          <span class="px-2 py-0.5 bg-white/20 rounded text-xs">{{ getLocalizedVolatility(nextMonthData.volatility) }}</span>
        </div>
      </div>
    </div>

    <!-- Period Summary -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
      <!-- Strong Period -->
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-green-500">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-2">
          {{ t('tools.seasonality.bestSixMonths') }}
        </h3>
        <p class="text-sm text-gray-600 dark:text-gray-400 mb-3">
          {{ t('tools.seasonality.strongPeriodDesc') }}
        </p>
        <div class="text-2xl font-bold text-green-600 dark:text-green-400 mb-2">
          {{ formatReturn(strongPeriodReturn) }}
        </div>
        <div class="flex flex-wrap gap-1">
          <span v-for="m in strongPeriodMonths" :key="m" class="px-2 py-1 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 rounded text-xs">
            {{ getLocalizedShortName(m) }}
          </span>
        </div>
      </div>

      <!-- Weak Period -->
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 border-l-4 border-amber-500">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-2">
          {{ t('tools.seasonality.weakSixMonths') }}
        </h3>
        <p class="text-sm text-gray-600 dark:text-gray-400 mb-3">
          {{ t('tools.seasonality.weakPeriodDesc') }}
        </p>
        <div class="text-2xl font-bold" :class="weakPeriodReturn >= 0 ? 'text-amber-600 dark:text-amber-400' : 'text-red-600 dark:text-red-400'">
          {{ formatReturn(weakPeriodReturn) }}
        </div>
        <div class="flex flex-wrap gap-1">
          <span v-for="m in weakPeriodMonths" :key="m" class="px-2 py-1 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300 rounded text-xs">
            {{ getLocalizedShortName(m) }}
          </span>
        </div>
      </div>
    </div>

    <!-- Best & Worst Months -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
      <!-- Best Months -->
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
          <Icon name="heroicons:arrow-trending-up" class="w-5 h-5 text-green-500" />
          {{ t('tools.seasonality.bestMonths') }}
        </h3>
        <div class="space-y-3">
          <div v-for="(month, index) in bestMonths" :key="month.month" class="flex items-center gap-3">
            <span class="w-6 h-6 flex items-center justify-center bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300 rounded-full text-xs font-bold">
              {{ index + 1 }}
            </span>
            <span class="font-medium text-gray-900 dark:text-white">{{ getLocalizedName(month.month) }}</span>
            <span class="ml-auto font-bold text-green-600 dark:text-green-400">{{ formatReturn(month.avgReturn) }}</span>
          </div>
        </div>
      </div>

      <!-- Worst Months -->
      <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
          <Icon name="heroicons:arrow-trending-down" class="w-5 h-5 text-red-500" />
          {{ t('tools.seasonality.worstMonths') }}
        </h3>
        <div class="space-y-3">
          <div v-for="(month, index) in worstMonths" :key="month.month" class="flex items-center gap-3">
            <span class="w-6 h-6 flex items-center justify-center bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 rounded-full text-xs font-bold">
              {{ index + 1 }}
            </span>
            <span class="font-medium text-gray-900 dark:text-white">{{ getLocalizedName(month.month) }}</span>
            <span class="ml-auto font-bold" :class="getReturnColorClass(month.avgReturn)">{{ formatReturn(month.avgReturn) }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- All Months Table -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-8">
      <div class="flex items-center justify-between mb-4">
        <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
          {{ t('tools.seasonality.allMonthsTable') }}
        </h3>
        <button
          @click="copyToClipboard"
          class="inline-flex items-center px-3 py-1.5 text-sm font-medium rounded-lg transition-all bg-indigo-600 hover:bg-indigo-700 text-white"
        >
          <Icon
            :name="copySuccess ? 'heroicons:check' : 'heroicons:clipboard-document'"
            class="w-4 h-4 mr-1"
          />
          {{ copySuccess ? t('common.copied') : t('common.copy') }}
        </button>
      </div>

      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead>
            <tr class="border-b border-gray-200 dark:border-gray-700">
              <th class="text-left py-3 px-2 font-medium text-gray-700 dark:text-gray-300">{{ t('tools.seasonality.month') }}</th>
              <th class="text-right py-3 px-2 font-medium text-gray-700 dark:text-gray-300">{{ t('tools.seasonality.avgReturn') }}</th>
              <th class="text-left py-3 px-2 font-medium text-gray-700 dark:text-gray-300">{{ t('tools.seasonality.characteristics') }}</th>
              <th class="text-center py-3 px-2 font-medium text-gray-700 dark:text-gray-300">{{ t('tools.seasonality.volatility') }}</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="month in monthlyData"
              :key="month.month"
              class="border-b border-gray-100 dark:border-gray-700/50 hover:bg-gray-50 dark:hover:bg-gray-700/30 transition-colors"
              :class="{ 'bg-indigo-50 dark:bg-indigo-900/20': month.month === currentMonth }"
            >
              <td class="py-3 px-2">
                <div class="flex items-center gap-2">
                  <span class="font-medium text-gray-900 dark:text-white">{{ getLocalizedShortName(month.month) }}</span>
                  <span v-if="month.month === currentMonth" class="px-1.5 py-0.5 bg-indigo-500 text-white text-xs rounded">
                    {{ t('tools.seasonality.now') }}
                  </span>
                </div>
              </td>
              <td class="py-3 px-2 text-right">
                <span class="font-bold" :class="getReturnColorClass(month.avgReturn)">
                  {{ formatReturn(month.avgReturn) }}
                </span>
              </td>
              <td class="py-3 px-2 text-gray-600 dark:text-gray-400 max-w-xs truncate">
                {{ t(month.characteristicsKey) }}
              </td>
              <td class="py-3 px-2 text-center">
                <span class="px-2 py-1 rounded text-xs font-medium" :class="getVolatilityColorClass(month.volatility)">
                  {{ getLocalizedVolatility(month.volatility) }}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Investment Recommendations -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-8">
      <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
        <Icon name="heroicons:light-bulb" class="w-5 h-5 text-amber-500" />
        {{ t('tools.seasonality.recommendations') }}
      </h3>
      <ul class="space-y-3">
        <li class="flex items-start gap-3">
          <Icon name="heroicons:check-circle" class="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
          <span class="text-gray-700 dark:text-gray-300">{{ t('tools.seasonality.recommendationsList.0') }}</span>
        </li>
        <li class="flex items-start gap-3">
          <Icon name="heroicons:check-circle" class="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
          <span class="text-gray-700 dark:text-gray-300">{{ t('tools.seasonality.recommendationsList.1') }}</span>
        </li>
        <li class="flex items-start gap-3">
          <Icon name="heroicons:check-circle" class="w-5 h-5 text-green-500 mt-0.5 flex-shrink-0" />
          <span class="text-gray-700 dark:text-gray-300">{{ t('tools.seasonality.recommendationsList.2') }}</span>
        </li>
      </ul>
    </div>

    <!-- Disclaimer -->
    <div class="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4 mb-8">
      <div class="flex items-start gap-3">
        <Icon name="heroicons:exclamation-triangle" class="w-5 h-5 text-amber-600 dark:text-amber-400 mt-0.5 flex-shrink-0" />
        <div class="text-sm text-amber-800 dark:text-amber-200">
          <p class="font-medium mb-1">{{ t('tools.seasonality.disclaimerTitle') }}</p>
          <p>{{ t('tools.seasonality.disclaimer') }}</p>
        </div>
      </div>
    </div>

    <!-- Data Source -->
    <div class="text-center text-sm text-gray-500 dark:text-gray-400">
      {{ t('tools.seasonality.dataSource') }}
    </div>
  </div>
</template>
