<script setup lang="ts">
import {
  monthlyData,
  getMonthName,
  getMonthShortName,
  getVolatilityLabel,
  getStrengthLabel,
  getMonthStrength,
  formatReturn,
  getReturnColorClass,
  getVolatilityColorClass,
  getBestMonths,
  getWorstMonths,
  calculatePeriodAvgReturn,
  analyzeSeasonality
} from '~/utils/stockSeasonality'
import type { VolatilityLevel } from '~/utils/stockSeasonality'

const { t, locale } = useI18n()
const toast = useToast()

const currentMonth = new Date().getMonth() + 1
const nextMonth = currentMonth === 12 ? 1 : currentMonth + 1

const currentMonthData = computed(() => monthlyData.find(m => m.month === currentMonth)!)
const nextMonthData = computed(() => monthlyData.find(m => m.month === nextMonth)!)
const bestMonths = computed(() => getBestMonths(3))
const worstMonths = computed(() => getWorstMonths(3))

const strongPeriodMonths = [11, 12, 1, 2, 3, 4]
const weakPeriodMonths = [5, 6, 7, 8, 9, 10]

const strongPeriodReturn = computed(() => calculatePeriodAvgReturn(strongPeriodMonths))
const weakPeriodReturn = computed(() => calculatePeriodAvgReturn(weakPeriodMonths))
const analysis = computed(() => analyzeSeasonality())

const getLocalizedName = (month: number) => getMonthName(month, locale.value)
const getLocalizedShortName = (month: number) => getMonthShortName(month, locale.value)
const getLocalizedVolatility = (volatility: VolatilityLevel) => getVolatilityLabel(volatility, locale.value)
const getLocalizedStrength = (avgReturn: number) => getStrengthLabel(getMonthStrength(avgReturn), locale.value)

const getCharacteristics = (month: number) => {
  const monthData = monthlyData.find(m => m.month === month)
  if (!monthData) return ''
  return t(monthData.characteristicsKey)
}

const copySuccess = ref(false)

const copyToClipboard = async () => {
  const lines: string[] = []

  if (locale.value === 'en') {
    lines.push('# US Stock Market Seasonality Analysis')
    lines.push('')
    lines.push('> Based on historical data from 1950 to present. Statistical patterns, not absolute predictions.')
    lines.push('')
    lines.push('## Monthly Performance Overview')
    lines.push('')
    lines.push('| Month | Avg Return | Characteristics | Volatility |')
    lines.push('|-------|------------|-----------------|------------|')

    for (const data of monthlyData) {
      lines.push(`| ${getMonthShortName(data.month, 'en')} | ${formatReturn(data.avgReturn)} | ${t(data.characteristicsKey, 'en')} | ${getVolatilityLabel(data.volatility, 'en')} |`)
    }
  } else {
    const isTraditional = locale.value === 'zh-TW'
    lines.push(isTraditional ? '# 美股月份季節性分析' : '# 美股月份季节性分析')
    lines.push('')
    lines.push(isTraditional
      ? '> 基於1950年至今的歷史數據統計，為統計模式而非絕對預測。'
      : '> 基于1950年至今的历史数据统计，为统计模式而非绝对预测。')
    lines.push('')
    lines.push(isTraditional ? '## 月份表現概覽' : '## 月份表现概览')
    lines.push('')
    lines.push('| 月份 | 平均回報 | 主要特性 | 波動性 |')
    lines.push('|------|----------|----------|--------|')

    for (const data of monthlyData) {
      lines.push(`| ${getMonthShortName(data.month, locale.value)} | ${formatReturn(data.avgReturn)} | ${t(data.characteristicsKey)} | ${getVolatilityLabel(data.volatility, locale.value)} |`)
    }
  }

  lines.push('')
  lines.push('---')
  lines.push('*Generated by Stock Seasonality Analyzer*')

  try {
    await navigator.clipboard.writeText(lines.join('\n'))
    copySuccess.value = true
    toast.success(t('tools.seasonality.copySuccess'))
    setTimeout(() => {
      copySuccess.value = false
    }, 2000)
  } catch {
    toast.error(t('tools.seasonality.copyFailed'))
  }
}

useHead({
  title: '美股月份季節性分析 - 投資工具',
  meta: [
    { name: 'description', content: '基於1950年至今的歷史數據，分析美股S&P 500月份季節性模式，了解最佳與最差月份，輔助投資決策。' }
  ]
})

definePageMeta({
  requiresAuth: false
})
</script>

<template>
  <div class="seasonality-page min-h-screen">
    <section class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <div class="panel overflow-hidden p-6 sm:p-8">
        <div class="grid gap-8 lg:grid-cols-[1.15fr_0.95fr] lg:items-center">
          <div>
            <p class="kicker mb-3">{{ t('tools.seasonality.heroKicker') }}</p>
            <h1 class="text-3xl font-semibold tracking-tight text-slate-900 dark:text-slate-100 sm:text-4xl">
              {{ t('tools.seasonality.title') }}
            </h1>
            <p class="mt-3 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300 sm:text-base">
              {{ t('tools.seasonality.subtitle') }}
            </p>

            <div class="mt-6 grid gap-3 sm:grid-cols-3">
              <div class="metric-card">
                <div class="metric-label">{{ t('tools.seasonality.currentMonth') }}</div>
                <div class="metric-value">{{ formatReturn(currentMonthData.avgReturn) }}</div>
              </div>
              <div class="metric-card">
                <div class="metric-label">{{ t('tools.seasonality.nextMonth') }}</div>
                <div class="metric-value">{{ formatReturn(nextMonthData.avgReturn) }}</div>
              </div>
              <div class="metric-card">
                <div class="metric-label">{{ t('tools.seasonality.bestMonths') }}</div>
                <div class="metric-value">{{ getLocalizedName(bestMonths[0]!.month) }}</div>
              </div>
            </div>
          </div>

          <div class="hero-spotlight">
            <div class="hero-spotlight-label">{{ t('tools.seasonality.bestSixMonths') }}</div>
            <div class="hero-spotlight-value">{{ formatReturn(strongPeriodReturn) }}</div>
            <p class="text-sm leading-6 text-slate-300">
              {{ t(analysis.strongPeriod.descriptionKey) }}
            </p>

            <div class="mt-6 flex flex-wrap gap-2">
              <span v-for="m in strongPeriodMonths" :key="m" class="month-pill">
                {{ getLocalizedShortName(m) }}
              </span>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="mx-auto grid max-w-7xl gap-6 px-4 pb-12 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:px-8">
      <div class="space-y-6">
        <div class="grid gap-6 xl:grid-cols-2">
          <div class="month-highlight month-highlight-current">
            <div class="flex items-center justify-between gap-4">
              <div>
                <p class="text-xs font-semibold uppercase tracking-[0.16em] text-sky-100/80">{{ t('tools.seasonality.currentMonth') }}</p>
                <h2 class="mt-2 text-3xl font-semibold text-white">{{ getLocalizedName(currentMonth) }}</h2>
              </div>
              <span class="highlight-badge">{{ getLocalizedStrength(currentMonthData.avgReturn) }}</span>
            </div>
            <div class="mt-5 text-4xl font-semibold text-white">{{ formatReturn(currentMonthData.avgReturn) }}</div>
            <p class="mt-3 text-sm leading-6 text-sky-100/85">{{ getCharacteristics(currentMonth) }}</p>

            <div class="mt-5 grid gap-2">
              <div v-for="reason in currentMonthData.possibleReasonsKeys" :key="reason" class="reason-row">
                <Icon name="heroicons:arrow-trending-up" class="h-4 w-4 text-sky-200" />
                <span>{{ t(reason) }}</span>
              </div>
            </div>
          </div>

          <div class="month-highlight month-highlight-next">
            <div class="flex items-center justify-between gap-4">
              <div>
                <p class="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-100/80">{{ t('tools.seasonality.nextMonth') }}</p>
                <h2 class="mt-2 text-3xl font-semibold text-white">{{ getLocalizedName(nextMonth) }}</h2>
              </div>
              <span class="highlight-badge">{{ getLocalizedStrength(nextMonthData.avgReturn) }}</span>
            </div>
            <div class="mt-5 text-4xl font-semibold text-white">{{ formatReturn(nextMonthData.avgReturn) }}</div>
            <p class="mt-3 text-sm leading-6 text-emerald-100/85">{{ getCharacteristics(nextMonth) }}</p>

            <div class="mt-5 grid gap-2">
              <div v-for="reason in nextMonthData.possibleReasonsKeys" :key="reason" class="reason-row">
                <Icon name="heroicons:arrow-path-rounded-square" class="h-4 w-4 text-emerald-200" />
                <span>{{ t(reason) }}</span>
              </div>
            </div>
          </div>
        </div>

        <div class="panel p-6 sm:p-7">
          <div class="mb-5 flex items-center justify-between gap-4">
            <div>
              <p class="kicker mb-2">{{ t('tools.seasonality.mapTitle') }}</p>
              <h3 class="text-xl font-semibold text-slate-900 dark:text-slate-100">{{ t('tools.seasonality.mapTitle') }}</h3>
            </div>
            <button type="button" class="action-btn cursor-pointer" @click="copyToClipboard">
              <Icon :name="copySuccess ? 'heroicons:check' : 'heroicons:clipboard-document'" class="mr-2 h-4 w-4" />
              {{ copySuccess ? t('common.copied') : t('common.copy') }}
            </button>
          </div>

          <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            <div
              v-for="month in monthlyData"
              :key="month.month"
              class="month-card"
              :class="month.month === currentMonth ? 'month-card-current' : ''"
            >
              <div class="flex items-start justify-between gap-3">
                <div>
                  <div class="text-sm font-semibold text-slate-900 dark:text-slate-100">
                    {{ getLocalizedName(month.month) }}
                  </div>
                  <div class="mt-1 text-xs uppercase tracking-[0.14em] text-slate-500 dark:text-slate-400">
                    {{ getLocalizedStrength(month.avgReturn) }}
                  </div>
                </div>
                <span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="getVolatilityColorClass(month.volatility)">
                  {{ getLocalizedVolatility(month.volatility) }}
                </span>
              </div>

              <div class="mt-4 text-2xl font-semibold" :class="getReturnColorClass(month.avgReturn)">
                {{ formatReturn(month.avgReturn) }}
              </div>
              <p class="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">
                {{ t(month.characteristicsKey) }}
              </p>
            </div>
          </div>
        </div>

        <div class="panel p-6 sm:p-7">
          <div class="mb-5 flex items-center justify-between gap-4">
            <div>
              <p class="kicker mb-2">{{ t('tools.seasonality.allMonthsTable') }}</p>
              <h3 class="text-xl font-semibold text-slate-900 dark:text-slate-100">
                {{ t('tools.seasonality.allMonthsTable') }}
              </h3>
            </div>
            <div class="text-xs uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400">
              {{ t('tools.seasonality.dataPeriod') }}
            </div>
          </div>

          <div class="overflow-x-auto">
            <table class="min-w-full text-sm">
              <thead>
                <tr class="border-b border-slate-200 dark:border-slate-800">
                  <th class="py-3 pr-4 text-left font-medium text-slate-500 dark:text-slate-300">{{ t('tools.seasonality.month') }}</th>
                  <th class="px-4 py-3 text-right font-medium text-slate-500 dark:text-slate-300">{{ t('tools.seasonality.avgReturn') }}</th>
                  <th class="px-4 py-3 text-left font-medium text-slate-500 dark:text-slate-300">{{ t('tools.seasonality.characteristics') }}</th>
                  <th class="pl-4 py-3 text-center font-medium text-slate-500 dark:text-slate-300">{{ t('tools.seasonality.volatility') }}</th>
                </tr>
              </thead>
              <tbody>
                <tr
                  v-for="month in monthlyData"
                  :key="month.month"
                  class="border-b border-slate-100 transition-colors dark:border-slate-800/70"
                  :class="month.month === currentMonth ? 'bg-blue-50/70 dark:bg-slate-900/80' : ''"
                >
                  <td class="py-4 pr-4">
                    <div class="flex items-center gap-2">
                      <span class="font-medium text-slate-900 dark:text-slate-100">{{ getLocalizedShortName(month.month) }}</span>
                      <span v-if="month.month === currentMonth" class="rounded-full bg-blue-600 px-2 py-0.5 text-[11px] font-semibold text-white">
                        {{ t('tools.seasonality.now') }}
                      </span>
                    </div>
                  </td>
                  <td class="px-4 py-4 text-right font-semibold" :class="getReturnColorClass(month.avgReturn)">
                    {{ formatReturn(month.avgReturn) }}
                  </td>
                  <td class="px-4 py-4 text-slate-600 dark:text-slate-300">
                    {{ t(month.characteristicsKey) }}
                  </td>
                  <td class="pl-4 py-4 text-center">
                    <span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="getVolatilityColorClass(month.volatility)">
                      {{ getLocalizedVolatility(month.volatility) }}
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="space-y-6">
        <div class="panel p-6 sm:p-7">
          <div class="mb-5 flex items-center justify-between gap-4">
            <div>
              <p class="kicker mb-2">{{ t('tools.seasonality.bestMonths') }}</p>
              <h3 class="text-xl font-semibold text-slate-900 dark:text-slate-100">
                {{ t('tools.seasonality.bestMonths') }}
              </h3>
            </div>
            <Icon name="heroicons:arrow-trending-up" class="h-5 w-5 text-emerald-500" />
          </div>

          <div class="space-y-3">
            <div v-for="(month, index) in bestMonths" :key="month.month" class="leader-row">
              <div class="flex items-center gap-3">
                <span class="rank-badge rank-badge-positive">{{ index + 1 }}</span>
                <div>
                  <div class="text-sm font-semibold text-slate-900 dark:text-slate-100">{{ getLocalizedName(month.month) }}</div>
                  <div class="text-xs text-slate-500 dark:text-slate-400">{{ getLocalizedVolatility(month.volatility) }}</div>
                </div>
              </div>
              <span class="text-lg font-semibold text-emerald-600 dark:text-emerald-400">{{ formatReturn(month.avgReturn) }}</span>
            </div>
          </div>
        </div>

        <div class="panel p-6 sm:p-7">
          <div class="mb-5 flex items-center justify-between gap-4">
            <div>
              <p class="kicker mb-2">{{ t('tools.seasonality.worstMonths') }}</p>
              <h3 class="text-xl font-semibold text-slate-900 dark:text-slate-100">
                {{ t('tools.seasonality.worstMonths') }}
              </h3>
            </div>
            <Icon name="heroicons:arrow-trending-down" class="h-5 w-5 text-rose-500" />
          </div>

          <div class="space-y-3">
            <div v-for="(month, index) in worstMonths" :key="month.month" class="leader-row">
              <div class="flex items-center gap-3">
                <span class="rank-badge rank-badge-negative">{{ index + 1 }}</span>
                <div>
                  <div class="text-sm font-semibold text-slate-900 dark:text-slate-100">{{ getLocalizedName(month.month) }}</div>
                  <div class="text-xs text-slate-500 dark:text-slate-400">{{ getLocalizedVolatility(month.volatility) }}</div>
                </div>
              </div>
              <span class="text-lg font-semibold" :class="getReturnColorClass(month.avgReturn)">{{ formatReturn(month.avgReturn) }}</span>
            </div>
          </div>
        </div>

        <div class="panel p-6 sm:p-7">
          <p class="kicker mb-2">{{ t('tools.seasonality.regimeViewTitle') }}</p>
          <h3 class="text-xl font-semibold text-slate-900 dark:text-slate-100">{{ t('tools.seasonality.regimeViewTitle') }}</h3>

          <div class="mt-5 grid gap-4">
            <div class="summary-card">
              <div class="summary-label">{{ t('tools.seasonality.bestSixMonths') }}</div>
              <div class="summary-value text-emerald-600 dark:text-emerald-400">{{ formatReturn(strongPeriodReturn) }}</div>
              <p class="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{{ t(analysis.strongPeriod.strategyKey) }}</p>
            </div>

            <div class="summary-card">
              <div class="summary-label">{{ t('tools.seasonality.weakSixMonths') }}</div>
              <div class="summary-value" :class="weakPeriodReturn >= 0 ? 'text-amber-600 dark:text-amber-400' : 'text-rose-600 dark:text-rose-400'">
                {{ formatReturn(weakPeriodReturn) }}
              </div>
              <p class="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{{ t(analysis.weakPeriod.strategyKey) }}</p>
            </div>
          </div>
        </div>

        <div class="panel p-6 sm:p-7">
          <h3 class="text-xl font-semibold text-slate-900 dark:text-slate-100">
            {{ t('tools.seasonality.recommendations') }}
          </h3>
          <ul class="mt-5 space-y-3">
            <li class="list-row">
              <Icon name="heroicons:check-circle" class="h-5 w-5 text-emerald-500" />
              <span>{{ t('tools.seasonality.recommendationsList.0') }}</span>
            </li>
            <li class="list-row">
              <Icon name="heroicons:check-circle" class="h-5 w-5 text-emerald-500" />
              <span>{{ t('tools.seasonality.recommendationsList.1') }}</span>
            </li>
            <li class="list-row">
              <Icon name="heroicons:check-circle" class="h-5 w-5 text-emerald-500" />
              <span>{{ t('tools.seasonality.recommendationsList.2') }}</span>
            </li>
          </ul>
        </div>

        <div class="warning-card">
          <Icon name="heroicons:exclamation-triangle" class="h-5 w-5 text-amber-500" />
          <div>
            <p class="text-sm font-semibold text-amber-900 dark:text-amber-200">{{ t('tools.seasonality.disclaimerTitle') }}</p>
            <p class="mt-2 text-sm leading-6 text-amber-800 dark:text-amber-100">{{ t('tools.seasonality.disclaimer') }}</p>
          </div>
        </div>

        <div class="text-center text-sm text-slate-500 dark:text-slate-400">
          {{ t('tools.seasonality.dataSource') }}
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&display=swap');

.seasonality-page {
  font-family: 'IBM Plex Sans', 'Avenir Next', 'Segoe UI', sans-serif;
  background:
    radial-gradient(900px 420px at 8% -8%, rgb(59 130 246 / 11%), transparent 62%),
    radial-gradient(820px 420px at 100% -8%, rgb(16 185 129 / 9%), transparent 62%),
    #f8fafc;
}

.panel {
  border: 1px solid rgb(191 219 254);
  border-radius: 1rem;
  background: rgb(255 255 255 / 84%);
  backdrop-filter: blur(8px);
  box-shadow: 0 12px 26px rgb(30 64 175 / 8%);
}

.kicker {
  font-size: 0.72rem;
  text-transform: uppercase;
  letter-spacing: 0.15em;
  color: rgb(59 130 246);
  font-weight: 700;
}

.metric-card,
.summary-card,
.month-card {
  border: 1px solid rgb(226 232 240);
  border-radius: 0.95rem;
  background: rgb(255 255 255 / 70%);
  padding: 1rem;
}

.metric-label,
.summary-label,
.spotlight-stat-label {
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: rgb(100 116 139);
}

.metric-value,
.summary-value {
  margin-top: 0.5rem;
  display: block;
  font-size: 1.35rem;
  font-weight: 600;
  color: rgb(15 23 42);
}

.hero-spotlight,
.month-highlight {
  border-radius: 1rem;
  padding: 1.5rem;
  box-shadow: inset 0 1px 0 rgb(255 255 255 / 6%);
}

.hero-spotlight {
  border: 1px solid rgb(30 64 175 / 20%);
  background: linear-gradient(160deg, rgb(15 23 42), rgb(15 23 42 / 94%) 48%, rgb(30 41 59) 100%);
}

.month-highlight-current {
  background:
    radial-gradient(circle at top right, rgb(56 189 248 / 26%), transparent 30%),
    linear-gradient(145deg, rgb(14 116 144), rgb(15 23 42));
}

.month-highlight-next {
  background:
    radial-gradient(circle at top right, rgb(52 211 153 / 25%), transparent 30%),
    linear-gradient(145deg, rgb(5 150 105), rgb(15 23 42));
}

.hero-spotlight-label {
  font-size: 0.72rem;
  font-weight: 700;
  letter-spacing: 0.16em;
  text-transform: uppercase;
  color: rgb(148 163 184);
}

.hero-spotlight-value {
  margin-top: 0.5rem;
  font-size: 2.5rem;
  font-weight: 600;
  color: white;
}

.month-pill,
.highlight-badge {
  border-radius: 999px;
  background: rgb(255 255 255 / 12%);
  padding: 0.45rem 0.8rem;
  font-size: 0.75rem;
  font-weight: 700;
  color: white;
}

.reason-row,
.leader-row,
.list-row {
  display: flex;
  gap: 0.65rem;
  align-items: flex-start;
}

.reason-row {
  font-size: 0.9rem;
  color: white;
  opacity: 0.92;
}

.leader-row {
  align-items: center;
  justify-content: space-between;
  border: 1px solid rgb(226 232 240);
  border-radius: 0.95rem;
  background: rgb(248 250 252 / 70%);
  padding: 0.9rem 1rem;
}

.rank-badge {
  display: inline-flex;
  height: 2rem;
  width: 2rem;
  align-items: center;
  justify-content: center;
  border-radius: 999px;
  font-size: 0.85rem;
  font-weight: 700;
}

.rank-badge-positive {
  background: rgb(220 252 231);
  color: rgb(21 128 61);
}

.rank-badge-negative {
  background: rgb(255 228 230);
  color: rgb(190 24 93);
}

.month-card-current {
  border-color: rgb(59 130 246);
  background: rgb(239 246 255 / 82%);
}

.action-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 0.8rem;
  padding: 0.7rem 1rem;
  color: white;
  background: rgb(30 64 175 / 88%);
  transition: background-color 180ms ease;
}

.action-btn:hover {
  background: rgb(29 78 216);
}

.warning-card {
  display: flex;
  gap: 0.75rem;
  border: 1px solid rgb(253 230 138);
  border-radius: 1rem;
  background: rgb(254 252 232);
  padding: 1rem;
}

:global(.dark .seasonality-page),
:global(.dark-mode .seasonality-page) {
  background:
    radial-gradient(900px 420px at 8% -8%, rgb(59 130 246 / 9%), transparent 62%),
    radial-gradient(820px 420px at 100% -8%, rgb(16 185 129 / 7%), transparent 62%),
    rgb(2 6 18);
}

:global(.dark .panel),
:global(.dark-mode .panel) {
  border-color: rgb(71 85 105);
  background: rgb(3 10 24 / 92%);
  box-shadow: 0 12px 26px rgb(2 6 23 / 45%);
}

:global(.dark .metric-card),
:global(.dark .summary-card),
:global(.dark .month-card),
:global(.dark .leader-row),
:global(.dark-mode .metric-card),
:global(.dark-mode .summary-card),
:global(.dark-mode .month-card),
:global(.dark-mode .leader-row) {
  border-color: rgb(51 65 85);
  background: rgb(8 15 30 / 78%);
}

:global(.dark .metric-label),
:global(.dark .summary-label),
:global(.dark-mode .metric-label),
:global(.dark-mode .summary-label) {
  color: rgb(148 163 184);
}

:global(.dark .metric-value),
:global(.dark .summary-value),
:global(.dark-mode .metric-value),
:global(.dark-mode .summary-value) {
  color: rgb(241 245 249);
}

:global(.dark .month-card-current),
:global(.dark-mode .month-card-current) {
  border-color: rgb(96 165 250);
  background: rgb(15 23 42);
}

:global(.dark .rank-badge-positive),
:global(.dark-mode .rank-badge-positive) {
  background: rgb(20 83 45);
  color: rgb(187 247 208);
}

:global(.dark .rank-badge-negative),
:global(.dark-mode .rank-badge-negative) {
  background: rgb(76 5 25);
  color: rgb(251 207 232);
}

:global(.dark .warning-card),
:global(.dark-mode .warning-card) {
  border-color: rgb(120 53 15);
  background: rgb(69 26 3 / 35%);
}
</style>
