-- CreateTable
CREATE TABLE `market_rotation_snapshot` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `date` DATE NOT NULL,
    `symbol` VARCHAR(20) NOT NULL,
    `rank_scope` VARCHAR(20) NOT NULL,
    `group_type` VARCHAR(20) NOT NULL,
    `sector_name` VARCHAR(100) NULL,
    `last_price` DECIMAL(18, 6) NULL,
    `adjusted_close` DECIMAL(18, 6) NULL,
    `daily_change_pct` DECIMAL(10, 4) NULL,
    `weekly_change_pct` DECIMAL(10, 4) NULL,
    `two_week_performance_pct` DECIMAL(10, 4) NULL,
    `rsi14` DECIMAL(8, 4) NULL,
    `rsi_percentile` DECIMAL(8, 4) NULL,
    `rsi_delta_2w` DECIMAL(8, 4) NULL,
    `ema10` DECIMAL(18, 6) NULL,
    `ema20` DECIMAL(18, 6) NULL,
    `sma50` DECIMAL(18, 6) NULL,
    `sma200` DECIMAL(18, 6) NULL,
    `above10d` BOOLEAN NULL,
    `above20d` BOOLEAN NULL,
    `above50d` BOOLEAN NULL,
    `above200d` BOOLEAN NULL,
    `ma_score` INT NULL,
    `ma_score_percentile` DECIMAL(8, 4) NULL,
    `ma_status` VARCHAR(32) NULL,
    `rolling_252d_high` DECIMAL(18, 6) NULL,
    `percent_from_high` DECIMAL(10, 4) NULL,
    `distance_from_high_score` DECIMAL(8, 4) NULL,
    `distance_from_high_score_percentile` DECIMAL(8, 4) NULL,
    `rotation_score` DECIMAL(8, 4) NULL,
    `rotation_score_delta_2w` DECIMAL(8, 4) NULL,
    `rotation_rank` INT NULL,
    `rank_delta_2w` INT NULL,
    `signal` VARCHAR(32) NULL,
    `signal_status` VARCHAR(32) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `market_rotation_snapshot_scope_symbol_date_key`(`rank_scope`, `symbol`, `date`),
    INDEX `market_rotation_snapshot_scope_date_rank_idx`(`rank_scope`, `date`, `rotation_rank`),
    INDEX `market_rotation_snapshot_scope_date_idx`(`rank_scope`, `date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
