// lib/errors/codes.ts

/**
 * 全系統錯誤代碼定義
 * 命名規則：MODULE_ACTION_REASON
 */
export const ErrorCodes = {
  // Auth
  AUTH_LOGIN_INVALID_CREDENTIALS: 'AUTH_LOGIN_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_NO_REFRESH_TOKEN: 'AUTH_NO_REFRESH_TOKEN',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',

  // Diary
  DIARY_NOT_FOUND: 'DIARY_NOT_FOUND',
  DIARY_ACCESS_DENIED: 'DIARY_ACCESS_DENIED',
  DIARY_ALREADY_EXISTS: 'DIARY_ALREADY_EXISTS',

  // Alert
  ALERT_NOT_FOUND: 'ALERT_NOT_FOUND',
  ALERT_ACCESS_DENIED: 'ALERT_ACCESS_DENIED',

  // ETF
  ETF_NOT_FOUND: 'ETF_NOT_FOUND',
  ETF_ALREADY_IN_WATCHLIST: 'ETF_ALREADY_IN_WATCHLIST',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',

  // Blog
  BLOG_NOT_FOUND: 'BLOG_NOT_FOUND',

  // System
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  SYS_VALIDATION_ERROR: 'SYS_VALIDATION_ERROR',
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]
